### PR TITLE
Menu rewrite

### LINKED ISSUE #7: Menu & hamburger close
make the menu and hamburger closed after clicking on one link

### LINKED ISSUE #13: Remove Material-ui
We don't really need it.
Rewrite the menu but without MUI.

### PR DESCRIPTION
**Pull request by yonatansnir**
Removed MUI and fixed responsive.

### CODE REVIEW

**Review by kottuzik — COMMENTED** [review]
change padding-top of .sidenav to 53px

**Review by yonis9 — COMMENTED** [review]
Looks really good to me.
I've noted that in the Hamburger state's we have openMenu, and clickMenu, which behave very similarly, don't you think we can handle this with only one variable on the state?

**Comment by kottuzik** [comment]
> Looks really good to me.
> I've noted that in the Hamburger state's we have openMenu, and clickMenu, which behave very similarly, don't you think we can handle this with only one variable on the state?

Feel free to change it

**Comment by yonis9** [comment]
I changed it, I also changed the "line-through" text-decoration of completed tasks to not be shown in the clear task button.

**Comment by yonatansnir** [comment]
I've not notice to this... thank you. Amazing job friend! @yonis9

**Pull request merged**
